<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>regra_default</name>
  <uuid>141c8c28-f3fc-4298-8879-e9057f99b616</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Regra Defautl" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
