<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Teste Regra</name>
  <uuid>2e862b51-ce4b-4a2c-904c-16e2537c6d83</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the flex_base of 'Dados de Entrada' is at least <min> and less than <max>
    and the flex_simul of 'Dados de Entrada' is at least <min> and less than <max>
    and the Anos_de_Estudo of 'Dados de Entrada' is at least <min> and less than <max>
    and the Num_simulacoes of 'Dados de Entrada' is at least <min> and less than <max>
then
    set decision to "Valor Caculado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
