<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Avaliacao_Regras</name>
  <uuid>68b3980b-e5e1-4087-9551-386e08cc9d40</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to <a string> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
