<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Regra_Avaliacao_BlackWhite</name>
  <uuid>d978fe5a-a385-4d81-a9bb-01b6d6f52275</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to ValorTeste;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
