<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Avaliacao_Geral</name>
  <uuid>b6e1b627-693f-4470-8288-bdd27abb968f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add "Teste" to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
