<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>3b33b3b6-8b7d-4a7b-a857-9b5dbf3852d2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add "Teste" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
