<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>BlackWhite_ProximaPolitica</name>
  <uuid>38e3f6ed-1b6d-4102-845d-5ab637bee7d9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the acaoLiberacao of Entrada is "S"
    and the flAtivo of Entrada is "S"
then
    set the Retorno of decision to "Proxima Politica";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
