<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Regra_BlackWhite_FinalizarFluxo</name>
  <uuid>71ce68b6-bf2a-4af3-8a94-5acfce355496</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the flAtivo of Entrada is "S" 
    and the acaoLiberacao of Entrada is "N"
then
set the Retorno of decision to "Finalizar Fluxo";

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
