<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Validacao Default </name>
  <uuid>cbbac86e-7e8e-4b98-8719-6cc77e70e5bd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Resultado_BlackWhite where
        the Retorno is "Ativo N. Proxima Policita";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
