<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>3505ad6d-aec8-48c3-addc-a4f5fada1a33</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Resultado_Reneg where
        the Retorno is "Nenhum Regra Validada" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
