<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Tem_Reneg_Cancelada</name>
  <uuid>06028681-2fe1-4b14-b2bf-3fa65d5a3944</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the dtCancelamentoReneg of Entrada_Reneg is not empty 
    and the simuladorStatus of Entrada_Reneg is one of { "1", "2"}
then
add a new Resultado_Reneg where
        the Retorno is "Status 1 ou 2 e Data Cancelamento nao branco" to decision;

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
