<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Validar_Pessoa</name>
  <uuid>adea82c4-dc2f-476e-a22c-cf5f46ace598</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the tpPessoa of Input is "J"
then
    add a new Resultado_OutrasRegras where
        the Retorno is "Pessoa Juridica" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
