<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Regra Alocacao</name>
  <uuid>8b0b2369-e1ca-4291-a77c-8b868e2a5def</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the flex_base of 'Dados de Entrada' is at least 0 and less than 999999
    and the flex_simul of 'Dados de Entrada' is at least 0 and less than 99999
    and the Anos_de_Estudo of 'Dados de Entrada' is at least 0 and less than 99
    and the Num_simulacoes of 'Dados de Entrada' is at least 0 and less than 99999
then
    set decision to a new Saida_Python where 
    the Ano is 1 , 
    the Premio_a_Cobrar is 1 , 
    the Var95_Flex_base is 1 , 
    the Var95_Flex_Simulado is 1;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
