<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Valor Default</name>
  <uuid>ea9244e6-1aa4-4048-8425-acbcf703b7c4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Saida_Python where
        the Ano is 0, 
        the Premio_a_Cobrar is 0, 
        the Var95_Flex_base is 0, 
        the Var95_Flex_Simulado is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
